on: 
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name:  Get latest code
      uses: actions/checkout@v3
    
    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v2.0.0
      env:
        FTP_SERVER: ftpupload.net
        FTP_USERNAME: if0_35673475@github-workflow.42web.io
        FTP_PASSWORD: IangrlU1gYeEY
        LOCAL_DIR: /
        REMOTE_DIR: /home/vol6_7/infinityfree.com/if0_35673475
        METHOD: sftp
        PORT: 21
        ARGS: --verbose
        
