on: 
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name:  Get latest code
      uses: actions/checkout@v3
    
    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 185.27.134.222
        username: if0_35673475@github-workflow.42web.io
        password: IangrlU1gYeEY
